### ISSUE TITLE
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled

### ISSUE THREAD

**Issue by iwst121** [YuvalNirkin/face_swap#10]
Hello,
The cmd is  "./face_swap_batch --cfg test.cfg",and  I get err below:
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled

Can you give me some advises?Thanks!

some information:
face_swap-master/bin$ ./face_swap_batch --cfg test.cfg 
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled

face_swap-master/bin$ ldd face_swap_batch 
	linux-vdso.so.1 =>  (0x00007fffdb3fe000)
	/home/anaconda2/lib/libmkl_rt.so (0x00007f7bd12fd000)
	libQt5Widgets.so.5 => /home/anaconda2/lib/libQt5Widgets.so.5 (0x00007f7bd09f9000)
	libGLU.so.1 => /usr/lib/x86_64-linux-gnu/libGLU.so.1 (0x00007f7bd0762000)
	libGL.so.1 => /usr/lib/nvidia-375/libGL.so.1 (0x00007f7bd04d2000)
	libGLEW.so => /usr/local/lib/libGLEW.so (0x00007f7bd0241000)
	libdlib.so.19.4.99 => /usr/local/lib/libdlib.so.19.4.99 (0x00007f7bcfd09000)
	libopencv_calib3d.so.3.2 => /usr/local/lib/libopencv_calib3d.so.3.2 (0x00007f7bcf96e000)
	libopencv_features2d.so.3.2 => /usr/local/lib/libopencv_features2d.so.3.2 (0x00007f7bcf698000)
	libopencv_photo.so.3.2 => /usr/local/lib/libopencv_photo.so.3.2 (0x00007f7bcf217000)
	libcaffe.so.1.0.0-rc3 => /home/MLData/caffe-master/build/lib/libcaffe.so.1.0.0-rc3 (0x00007f7bceac6000)
	libopencv_imgcodecs.so.3.2 => /usr/local/lib/libopencv_imgcodecs.so.3.2 (0x00007f7bce704000)
	libopencv_imgproc.so.3.2 => /usr/local/lib/libopencv_imgproc.so.3.2 (0x00007f7bcced0000)
	libopencv_core.so.3.2 => /usr/local/lib/libopencv_core.so.3.2 (0x00007f7bcba51000)
	libboost_system.so.1.64.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.64.0 (0x00007f7bcb84c000)
	libglog.so.0 => /usr/lib/x86_64-linux-gnu/libglog.so.0 (0x00007f7bcb614000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7bcb3f6000)
	libhdf5.so.101 => /home/anaconda2/lib/libhdf5.so.101 (0x00007f7bcae33000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7bcab2d000)
	libhdf5_cpp.so.101 => /home/anaconda2/lib/libhdf5_cpp.so.101 (0x00007f7bca8c6000)
	libQt5Gui.so.5 => /home/anaconda2/lib/libQt5Gui.so.5 (0x00007f7bca09c000)
	libQt5Core.so.5 => /home/anaconda2/lib/libQt5Core.so.5 (0x00007f7bc994e000)
	libstdc++.so.6 => /home/anaconda2/lib/libstdc++.so.6 (0x00007f7bc963b000)
	libgcc_s.so.1 => /home/anaconda2/lib/libgcc_s.so.1 (0x00007f7bc9424000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7bc905b000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7bc8e57000)
	libGLX.so.0 => /usr/lib/nvidia-375/libGLX.so.0 (0x00007f7bc8c26000)
	libGLdispatch.so.0 => /usr/lib/nvidia-375/libGLdispatch.so.0 (0x00007f7bc893d000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f7bc8734000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f7bc83ff000)
	libpng16.so.16 => /home/anaconda2/lib/libpng16.so.16 (0x00007f7bc81bd000)
	libjpeg.so.9 => /home/anaconda2/lib/libjpeg.so.9 (0x00007f7bc7f80000)
	libcublas.so.8.0 => /usr/local/cuda/lib64/libcublas.so.8.0 (0x00007f7bc54e8000)
	libcudnn.so.5 => /usr/local/lib/libcudnn.so.5 (0x00007f7bc0714000)
	libcurand.so.8.0 => /usr/local/cuda/lib64/libcurand.so.8.0 (0x00007f7bbc79d000)
	libcusolver.so.8.0 => /usr/local/cuda/lib64/libcusolver.so.8.0 (0x00007f7bb922f000)
	libiomp5.so => /home/anaconda2/lib/libiomp5.so (0x00007f7bb8e85000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7bd1936000)
	libopencv_flann.so.3.2 => /usr/local/lib/libopencv_flann.so.3.2 (0x00007f7bb8c28000)
	libopencv_cudaimgproc.so.3.2 => /usr/local/lib/libopencv_cudaimgproc.so.3.2 (0x00007f7bb6f3c000)
	libcudart.so.8.0 => /usr/local/cuda/lib64/libcudart.so.8.0 (0x00007f7bb6cd5000)
	libopencv_cudaarithm.so.3.2 => /usr/local/lib/libopencv_cudaarithm.so.3.2 (0x00007f7badffa000)
	libboost_thread.so.1.64.0 => /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.64.0 (0x00007f7baddd2000)
	libgflags.so.2 => /usr/lib/x86_64-linux-gnu/libgflags.so.2 (0x00007f7badbb2000)
	libprotobuf.so.13 => /usr/local/lib/libprotobuf.so.13 (0x00007f7bad75b000)
	libhdf5_hl.so.100 => /home/anaconda2/lib/libhdf5_hl.so.100 (0x00007f7bad536000)
	liblmdb.so.0 => /usr/lib/x86_64-linux-gnu/liblmdb.so.0 (0x00007f7bad324000)
	libleveldb.so.1 => /usr/lib/x86_64-linux-gnu/libleveldb.so.1 (0x00007f7bad0d7000)
	libopenblas.so.0 => /opt/OpenBLAS/lib/libopenblas.so.0 (0x00007f7bac19d000)
	libpython2.7.so.1.0 => /home/anaconda2/lib/libpython2.7.so.1.0 (0x00007f7babda1000)
	libboost_python.so.1.64.0 => /usr/lib/x86_64-linux-gnu/libboost_python.so.1.64.0 (0x00007f7babb54000)
	libtiff.so.5 => /home/anaconda2/lib/libtiff.so.5 (0x00007f7bab8d5000)
	libjasper.so.1 => /usr/lib/x86_64-linux-gnu/libjasper.so.1 (0x00007f7bab67e000)
	libIlmImf.so.6 => /usr/lib/x86_64-linux-gnu/libIlmImf.so.6 (0x00007f7bab3ce000)
	libHalf.so.6 => /usr/lib/x86_64-linux-gnu/libHalf.so.6 (0x00007f7bab18b000)
	libz.so.1 => /usr/local/lib/libz.so.1 (0x00007f7baaf72000)
	libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007f7baad57000)
	libicui18n.so.54 => /home/anaconda2/lib/./libicui18n.so.54 (0x00007f7baa8f2000)
	libicuuc.so.54 => /home/anaconda2/lib/./libicuuc.so.54 (0x00007f7baa554000)
	libicudata.so.54 => /home/anaconda2/lib/./libicudata.so.54 (0x00007f7ba8b2a000)
	libgthread-2.0.so.0 => /home/anaconda2/lib/./libgthread-2.0.so.0 (0x00007f7ba8928000)
	libglib-2.0.so.0 => /home/anaconda2/lib/./libglib-2.0.so.0 (0x00007f7ba8611000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f7ba83fe000)
	libxcb.so.1 => /home/anaconda2/lib/libxcb.so.1 (0x00007f7ba81da000)
	libopencv_cudafilters.so.3.2 => /usr/local/lib/libopencv_cudafilters.so.3.2 (0x00007f7b90c1f000)
	libnppc.so.8.0 => /usr/local/cuda/lib64/libnppc.so.8.0 (0x00007f7b909af000)
	libnppi.so.8.0 => /usr/local/cuda/lib64/libnppi.so.8.0 (0x00007f7b89f8b000)
	libnpps.so.8.0 => /usr/local/cuda/lib64/libnpps.so.8.0 (0x00007f7b89594000)
	libcufft.so.8.0 => /usr/local/cuda/lib64/libcufft.so.8.0 (0x00007f7b80745000)
	libsnappy.so.1 => /usr/lib/libsnappy.so.1 (0x00007f7b8053e000)
	libgfortran.so.3 => /home/anaconda2/lib/libgfortran.so.3 (0x00007f7b80235000)
	libgomp.so.1 => /home/anaconda2/lib/libgomp.so.1 (0x00007f7b80026000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f7b7fe22000)
	liblzma.so.5 => /home/anaconda2/lib/./liblzma.so.5 (0x00007f7b7fbfd000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f7b7f9a8000)
	libIex.so.6 => /usr/lib/x86_64-linux-gnu/libIex.so.6 (0x00007f7b7f789000)
	libIlmThread.so.6 => /usr/lib/x86_64-linux-gnu/libIlmThread.so.6 (0x00007f7b7f583000)
	libpcre.so.1 => /home/anaconda2/lib/././libpcre.so.1 (0x00007f7b7f33f000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f7b7f13b000)

**Comment by YuvalNirkin** [comment]
What platform are you using? What graphic card do you have?

You probably have built Qt without OpenGL support.

**Comment by iwst121** [comment]
The platform is Ubuntu 14.04 LTS. The gpu is GeForce GTX 1080.

**Comment by YuvalNirkin** [comment]
This configuration should work fine.
The problem must be with Qt, try to configure and rebuild Qt with GLX or EGL enabled, or download the appropriate binaries.

If you can't make Qt work you can try the solution I suggested in #7.

**Comment by iwst121** [comment]
@YuvalNirkin Thanks. It is fixed by the soulution you suggested in #7.

But I have a new problem now.
When it is running on a remote linux server(a cloud machine) which is connected by ssh,I get the error messages:
freeglut (./face_swap_batch):  ERROR:  Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow

When I run glxinfo, get some info:
root@iZwz9eg6dz5zur0cg87u4hZ:/home#glxinfo
name of display: localhost:1
Error: couldn't find RGB GLX visual or fbconfig
Error: couldn't find RGB GLX visual or fbconfig



The new platform information:
root@iZwz9eg6dz5zur0cg87u4hZ:/home#cat /etc/issue
Ubuntu 14.04.5 LTS \n \l

root@iZwz9eg6dz5zur0cg87u4hZ:/home#nvidia-smi 
Fri Jul 28 11:02:23 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.51                 Driver Version: 375.51                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M40           On   | 0000:00:06.0     Off |                    0 |
| N/A   45C    P0    62W / 250W |   9931MiB / 11443MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by iwst121** [comment]
I have fixed it.Thanks all.
