### ISSUE TITLE
Doxygen generated documentation is not working

### ISSUE THREAD

**Issue by satvikmaker** [YuvalNirkin/face_swap#11]
Please can you share instructions on how to run the project?

Doxygen generated documentation is not working-
[http://nirkin.com/projects/face_swap/](http://nirkin.com/projects/face_swap/)

**Comment by YuvalNirkin** [comment]
The documentation is working, it includes details about the C++ classes.
For running the project I suggest you use the command line tools. I explain how to use them [here](https://github.com/YuvalNirkin/face_swap).
