### ISSUE TITLE
Confict with OpenCV3.3.0

### ISSUE THREAD

**Issue by halfkai** [YuvalNirkin/face_swap#12]
In OpenCV 3.3.0 and its contribs, it seems the functions like "cv2::face::createLBPHFaceRecognizer()" have been changed into "cv2::face::LBPHFaceRecognizer::create()"... and I've tried so many times and thought it was the compiling part went wrong... but it wasn't... so it would be nice to show that the version of OpenCV should below 3.3.0 :cry:

**Comment by YuvalNirkin** [comment]
Thanks for the feedback I'll fix it when I'll get the chance.
For now you can just build find_face_landmarks without the LBP tracker and it should work.
```
cmake -DWITH_OPENCV_CONTRIB=OFF 
```

**Comment by YuvalNirkin** [comment]
I fixed the conflict with OpenCV 3.3.x in find_face_landmarks:
[https://github.com/YuvalNirkin/find_face_landmarks/commit/69975ae2c4baf1d18a15a3a2068a68afcfbaa4f1](https://github.com/YuvalNirkin/find_face_landmarks/commit/69975ae2c4baf1d18a15a3a2068a68afcfbaa4f1)
