### ISSUE TITLE
Segmentation fault (core dumped) when running the demo 

### ISSUE THREAD

**Issue by hailehong** [YuvalNirkin/face_swap#13]
Hi,
I met this error when running the demo
I0921 13:13:41.511903 1711 net.cpp:242] This network produces output score
I0921 13:13:41.511961 1711 net.cpp:255] Network initialization done.
I0921 13:13:43.045377 1711 net.cpp:744] Ignoring source layer data
I0921 13:13:43.045660 1711 net.cpp:744] Ignoring source layer data_data_0_split
I0921 13:13:43.154325 1711 net.cpp:744] Ignoring source layer loss
**Segmentation fault (core dumped)**

I run the code in both GPU and CPU mode, using a computer with K40 GPU.
Did someone meet this error?

Thank you!

**Comment by zxwedu** [comment]
Hi, 
I meet the same error as you. Have you solved this problem? I find this error occurred in the rendering period. It is related to this function: glGenRenderbuffersEXT( 1, &g_depthRenderBuffer ); The function is a library function from GLEW. But  I have not solved the problem.
Thank you!

**Comment by YuvalNirkin** [comment]
Please make sure your system can provide a valid OpenGL context.

**Comment by zxwedu** [comment]
Thank you for your kind reply. I will make sure the valid OpenGL context. Would you mind telling me about your operating system when you run the code? My server is connected by ssh without the graphical interfaces. I want to confirm whether the Segmentation fault is related to this.
Thank you very much.

**Comment by YuvalNirkin** [comment]
Yes it is related. If you don't have a graphical interface then probably you also can't get a valid OpenGL context. This means all OpenGL function calls will fail.

**Comment by zxwedu** [comment]
Thank you for your great help.

**Comment by ypflll** [comment]
Hi, @zhouxiaowei1120 , @YuvalNirkin 
I also met this problem. It is clear that this is because OpenGL is constrained in VNC viewer or a CLI.
How to fix this? I tried VNC viewer or a CLI which didn't work.
Other ubuntu remote desktop recommend? Or use opencv instead of opengl?

**Comment by ypflll** [comment]
Two ways to solve my problem:
1.Do not use VNC viewer.  Connect to you machine locally and the code runs well.
2.Use teamviewer.

**Comment by zxwedu** [comment]
@ypflll yes,just as you said, I also solved the problem by these two methods.
