### ISSUE TITLE
always return cv:Mat()

### ISSUE THREAD

**Issue by rootkit** [YuvalNirkin/face_swap#14]
when the app run here: 
cv::Mat FaceSwap::blend(const cv::Mat& src, const cv::Mat& dst, const cv::Mat& dst_seg)
if (minc >= maxc || minr >= maxr) return cv::Mat();

blend always return cv:Mat(), I don't know what happen? 
BTW: I finish port the great app to iOS platform, in the end run here and stop, return failstd::runtime_error: Face swap failed!

Thanks

John

**Comment by YuvalNirkin** [comment]
This means that the combined segmentation map is only zeros.
It might be a problem with the landmarks or the segmentation.

I like the idea of an iOS port! It can be a great contribution! Are you willing to share the code?

**Comment by rootkit** [comment]
the log:
faces found = 1
faces found = 1
vecR [0.0029098843;
 0.15772882;
 -0.037092187]
vecT [1.9298197;
 -21.032534;
 -1098.7878]
exprW [-0.39331913;
 0.17700461;
 -0.29514793;
 0.11593564;
 -0.42752558;
 0.24469842;
 2.8671944;
 0.7221989;
 -1.1991261;
 0.099073336;
 0.20576096;
 1.0124749;
 -0.44310626;
 -0.098507486;
 -1.0734005;
 -0.24701883;
 -0.37821278;
 0.3187601;
 1.1587392;
 1.8510281;
 1.3205831;
 0.76069188;
 -0.029121373;
 -0.0070772283;
 1.1604365;
 0.0073522874;
 0.24649803;
 -0.02893436;
 -0.24754204]
vecR [-0.034498993;
 0.077174194;
 -0.13330679]
vecT [4.0268807;
 -32.977039;
 -924.23651]
exprW [-0.24939266;
 0.39104307;
 -0.17418325;
 0.77485698;
 -0.11051087;
 0.25302994;
 1.5111284;
 -1.7924082;
 -0.21672148;
 -0.19027816;
 -0.27793592;
 1.3636755;
 0.03324154;
 -0.012820265;
 -1.6727974;
 -0.12949848;
 -0.047394246;
 0.91332167;
 0.16732536;
 0.04252547;
 0.11279398;
 0.49106297;
 -0.008773597;
 -0.21201798;
 1.1952631;
 0.24981749;
 0.021493442;
 -0.29385114;
 -0.26967478]
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Face swap failed!

I found here :
        cv::Mat rendered_img;
        m_face_renderer->render(m_vecR, m_vecT);
        m_face_renderer->getFrameBuffer(rendered_img);
rendered_img data is zeros, I think the issues is here? Am I right?

I will share the porting code till the app can run on iOS, but I might not enough time to support the code.

**Comment by YuvalNirkin** [comment]
I can't track the problem from this log. What images have you used?

**Comment by rootkit** [comment]
I import some debug images, as follows:
cv::Mat debug_src_mesh_img = fs.debugSourceMesh();
cv::Mat debug_tgt_mesh_img = fs.debugTargetMesh();
![img_0195](https://user-images.githubusercontent.com/361834/32781508-4131e0d8-c980-11e7-8027-5c4599ca03b3.jpg)
![img_0194](https://user-images.githubusercontent.com/361834/32781515-4618d8ae-c980-11e7-9191-54c218046932.jpg)

 cv::Mat debug_src_lms_img = fs.debugSourceLandmarks();
cv::Mat debug_tgt_lms_img = fs.debugTargetLandmarks();
![img_0201](https://user-images.githubusercontent.com/361834/32781518-5016d388-c980-11e7-9f7d-821a982483fc.jpg)
![img_0202](https://user-images.githubusercontent.com/361834/32781683-e8afe030-c980-11e7-941e-3926f8259fae.jpg)


cv::Mat debug_src_mesh_wire_img = fs.debugSourceMeshWireframe();
cv::Mat debug_tgt_mesh_wire_img = fs.debugTargetMeshWireframe();
![img_0219](https://user-images.githubusercontent.com/361834/32781753-1e919b3a-c981-11e7-8c10-2e976e78e6ce.jpg)
![img_0254](https://user-images.githubusercontent.com/361834/32781760-2703545c-c981-11e7-9eef-4bae06446e87.jpg)

BTW: face segment need to big memory more then 1GB, I have to generate them by Mac OS APP
![src](https://user-images.githubusercontent.com/361834/32781781-3608cdd8-c981-11e7-84bc-9db4a94b55b4.png)
![des](https://user-images.githubusercontent.com/361834/32781788-3cd3ff5c-c981-11e7-8d24-f9aba0381297.png)

**Comment by rootkit** [comment]
I found the rendered_img.data is zero, so opengles porting is not right?
m_face_renderer->render(m_vecR, m_vecT);
m_face_renderer->getFrameBuffer(rendered_img);

**Comment by YuvalNirkin** [comment]
What is the OpenGL ES version? It has to be equivalent to OpenGL 1.5 (without shaders).

**Comment by rootkit** [comment]
#include <OpenGLES/ES1/gl.h>
#include <OpenGLES/ES1/glext.h>
#include <OpenGLES/ES2/gl.h>
#include <OpenGLES/ES2/glext.h>

**Comment by rootkit** [comment]
I have to use opengl es1, delete es2.0, now I test it... god bless me

**Comment by rootkit** [comment]
I already change opengl es2 to es1, no lucky:),   rendered_img is still zero. 
I ongly add a function beacause es2 does not provide it.
void gluPerspective(double fovy , double aspect , double zNear , double zFar)
{
    // Start in projection mode.
    //glMatrixMode(GL_PROJECTION);
    //glLoadIdentity();
    double xmin, xmax, ymin, ymax;
    ymax = zNear * tan(fovy * M_PI / 360.0);
    ymin = -ymax;
    xmin = ymin * aspect;
    xmax = ymax * aspect;
    glFrustumf(xmin, xmax, ymin, ymax, zNear, zFar);
}

**Comment by rootkit** [comment]
![2017-11-25 2 45 24](https://user-images.githubusercontent.com/361834/33228194-26394172-d1f0-11e7-82d2-6d48dfee1e03.png)
![2017-11-25 2 46 07](https://user-images.githubusercontent.com/361834/33228202-46852068-d1f0-11e7-86be-a7957afeb659.png)
![2017-11-25 2 47 19](https://user-images.githubusercontent.com/361834/33228204-4d85bb3e-d1f0-11e7-8b4c-3418c0b5b2fa.png)
![2017-11-25 3 05 20](https://user-images.githubusercontent.com/361834/33228284-6d34dd82-d1f2-11e7-864d-503b024e07e9.png)
![2017-11-25 3 05 31](https://user-images.githubusercontent.com/361834/33228285-730b12f8-d1f2-11e7-9cf3-105c03a05f1e.png)


Everything is ok but rendered_img:(

**Comment by rootkit** [comment]
So how to trace the problem in the next step? do you need more screetshots about it.
