### ISSUE TITLE
I am finding the below issue on (cmake find_face_landmarks) while using your code in c++,mac system #13

### ISSUE THREAD

**Issue by bmanimsc** [YuvalNirkin/face_swap#16]
Mac-mini:face_swap-master mani$ make
[ 20%] Building CXX object sequence_face_landmarks/CMakeFiles/sequence_face_landmarks.dir/sequence_face_landmarks.cpp.o
In file included from /Users/mani/Downloads/face_swap-master/find_face_landmarks-master/sequence_face_landmarks/sequence_face_landmarks.cpp:20:
In file included from /usr/local/Cellar/dlib/19.7/include/dlib/image_processing/render_face_detections.h:7:
In file included from /usr/local/Cellar/dlib/19.7/include/dlib/array2d/../geometry/../image_processing/../gui_widgets.h:13:
In file included from /usr/local/Cellar/dlib/19.7/include/dlib/gui_widgets/widgets.h:16:
In file included from /usr/local/Cellar/dlib/19.7/include/dlib/gui_widgets/drawable.h:10:
In file included from /usr/local/Cellar/dlib/19.7/include/dlib/gui_widgets/../gui_core.h:14:
In file included from /usr/local/Cellar/dlib/19.7/include/dlib/gui_core/xlib.h:4:
/usr/local/Cellar/dlib/19.7/include/dlib/gui_core/gui_core_kernel_2.h:11:2: error: "DLIB_NO_GUI_SUPPORT is defined so you can't use the GUI code.  Turn DLIB_NO_GUI_SUPPORT off if you want to use it."
#error "DLIB_NO_GUI_SUPPORT is defined so you can't use the GUI code.  Turn DLIB_NO_GUI_SUPPORT off if you want to use it."
 ^
/usr/local/Cellar/dlib/19.7/include/dlib/gui_core/gui_core_kernel_2.h:12:2: error: "Also make sure you have libx11-dev installed on your system"
#error "Also make sure you have libx11-dev installed on your system"
 ^
2 errors generated.
make[2]: *** [sequence_face_landmarks/CMakeFiles/sequence_face_landmarks.dir/sequence_face_landmarks.cpp.o] Error 1
make[1]: *** [sequence_face_landmarks/CMakeFiles/sequence_face_landmarks.dir/all] Error 2
make: *** [all] Error 2

**Comment by YuvalNirkin** [comment]
Mac is not officially supported but you can disable the find_face_landmarks viewer.
