### ISSUE TITLE
QOpenGLContext create causes segmentation fault on linux

### ISSUE THREAD

**Issue by chrischen** [YuvalNirkin/face_swap#20]
Line 122 of face_swap_image.cpp:
```
        QOpenGLContext openGLContext;
        openGLContext.setFormat(surfaceFormat);
        openGLContext.create();
```

openGLContext.create() segmentation fault on Linux - Ubuntu 16.04.

**Comment by YuvalNirkin** [comment]
Make sure that it is possible to get a valid OpenGL context on your system.
If you are running on a server then it might not be available.
