### ISSUE TITLE
make  warning about glew and qt

### ISSUE THREAD

**Issue by tjusxh** [YuvalNirkin/face_swap#24]
When I make the project. I come across the following question. Anyone have suggestion how to solve the question?
In file included from /usr/local/Qt-5.8.0/include/QtGui/QOpenGLContext:1:0,
                 from /home/songxinhui/face_swap/face_swap_image/face_swap_image.cpp:27:
/usr/local/Qt-5.8.0/include/QtGui/qopenglcontext.h:55:2: **warning: #warning qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined [-Wcpp]**
 **#warning qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined**
  ^
/usr/local/Qt-5.8.0/include/QtGui/qopenglcontext.h:56:2: warning: #warning To use GLEW with Qt, do not include <qopengl.h> or <QOpenGLFunctions> after glew.h [-Wcpp]
 #warning To use GLEW with Qt, do not include <qopengl.h> or <QOpenGLFunctions> after glew.h
  ^
[ 90%] Linking CXX executable face_swap_image
[ 90%] Built target face_swap_image
[ 95%] Building CXX object face_swap_batch/CMakeFiles/face_swap_batch.dir/face_swap_batch.cpp.o
In file included from /usr/local/Qt-5.8.0/include/QtGui/QOpenGLContext:1:0,
                 from /home/songxinhui/face_swap/face_swap_batch/face_swap_batch.cpp:29:
/usr/local/Qt-5.8.0/include/QtGui/qopenglcontext.h:55:2: warning: #warning qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined [-Wcpp]
 #warning qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined
  ^
/usr/local/Qt-5.8.0/include/QtGui/qopenglcontext.h:56:2: warning: #warning To use GLEW with Qt, do not include <qopengl.h> or <QOpenGLFunctions> after glew.h [-Wcpp]
 #warning To use GLEW with Qt, do not include <qopengl.h> or <QOpenGLFunctions> after glew.h

**Comment by YuvalNirkin** [comment]
Ignore it.
