### ISSUE TITLE
QXcbConnection: Failed to initialize XRandr

### ISSUE THREAD

**Issue by tjusxh** [YuvalNirkin/face_swap#25]
When I try to run the demo. The following question occur.
I use the remote linux server by ssh in XShell. Anyone have some suggestion.

**QXcbConnection: Failed to initialize XRandr
Could not initialize GLX
Aborted (core dumped)**

I guess it is related with qt and opencv，but I don't know the detail , I am going to try.
Installing opencv, I don't sure if will the parameters -D WITH_QT=ON -D WITH_OPENGL=ON effect the function of qt ?

cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D FORCE_VTK=ON -D WITH_TBB=ON -D WITH_V4L=ON -D WITH_QT=ON -D WITH_OPENGL=ON -D WITH_CUBLAS=ON -D CUDA_NVCC_FLAGS="-D_FORCE_INLINES" -D WITH_GDAL=ON -D WITH_XINE=ON -D BUILD_EXAMPLES=ON ..

I reinstall opencv with_QT and with_OPENGL, but the issue still exist.  I had stuck two days, anyone can give the suggestion? I will very appreciate it.

**Comment by YuvalNirkin** [comment]
An OpenGL context is required for rendering and it is not available on your server.
