### ISSUE TITLE
Issues with installations

### ISSUE THREAD

**Issue by prabhakar267** [YuvalNirkin/face_swap#26]
I am new to C++ and I want to setup the system on my Linux (Ubuntu 14.04) machine, but I am not able to install it.
Could you help me with an "easier" to-understand setup guide (basically more verbose) elaborating on the ```Use CMake and your favorite compiler to build and install the library``` point

/cc @YuvalNirkin @TalHassner

**Comment by abhinavaggarwal018** [comment]
+1

**Comment by YuvalNirkin** [comment]
Will do.
