### ISSUE TITLE
Rotation and Translation doesn't seem right

### ISSUE THREAD

**Issue by RudyChin** [YuvalNirkin/face_swap#3]
I'm not sure what's wrong. I've dug into the code, I'm wondering is it because it rotates first before translation in `face_swap/face_renderer.cpp`?

The output doesn't seem right. (compared to images in the paper and #1 )
![brad_pitt_01_bruce_willis_01](https://user-images.githubusercontent.com/5927320/27019059-97a9a0c4-4f67-11e7-97d1-876197bc0ba3.jpg)
![brad_pitt_01_795](https://user-images.githubusercontent.com/5927320/27019068-9e9e7cb0-4f67-11e7-9fdc-5d367b2196fa.jpg)

I've tried out specifying translation manually, i.e. `glTranslatef(vecT.at<float>(0)+100, vecT.at<float>(1), vecT.at<float>(2));` and it works.
I've tried applying translation before rotation and rotate to a specific degree, i.e. `glRotatef(90, 0, 0, 1);`, and it works as expected (The mesh will rotate counter-clockwise for 90 degrees)

Do you know where I should dig in to fix this up?

Thanks

**Comment by YuvalNirkin** [comment]
You will have to provide more detail like your computer specs, os, library versions, etc..
The transformations in the code are all tested to be working on both Windows and Linux, there is no point in trying to change them.

**Comment by RudyChin** [comment]
Thanks for the reply!
I'm building up a docker container for this project
The system settings are as follows:

- Ubuntu 16.04
- Qt 5.4
- OpenCV 3.0
- GLEW 2.0
- HDF5 1.8.18
- Boost 1.58
- Dlib 19.4
- Protobuf 3.3.0
- Eigen 3
- Caffe 1.0
- vsal 1.0
- find_face_landmark 1.1
- face_segmentation 0.9

When I'm compiling this project, I got warnings as follows:

> /usr/local/Qt-5.4.2/include/QtGui/qopenglcontext.h:50:2: warning: #warning To use GLEW with Qt, do not include <qopengl.h> or <QOpenGLFunctions> after glew.h [-Wcpp]

Is it normal?

**Comment by RudyChin** [comment]
I'm wondering is it because I'm not using GPU for OpenGL acceleration?
I use pure CPU for the end-to-end task

**Comment by YuvalNirkin** [comment]
Yes, the software implementation of OpenGL can be problematic.

**Comment by RudyChin** [comment]
I tried it natively on Ubuntu 16.04 using Nvidia GPU (driver version 378) but still no luck.
I get the same result as I posted.
Would you mind sharing your environment information?

**Comment by RudyChin** [comment]
I got it right!!!!!!
![brad_pitt_01_795](https://user-images.githubusercontent.com/5927320/27341316-7e15802a-560f-11e7-8f51-5dc03166f11e.jpg)

I'll close this issue and file a pull request soon

**Comment by YuvalNirkin** [comment]
Congratulation! This looks good!
I commend you for your perseverance and a pull request will be very much appreciated.
