### ISSUE TITLE
how to train face segmentation model

### ISSUE THREAD

**Issue by rootkit** [YuvalNirkin/face_swap#32]
Hi YuvalNiirkin
I wanna train face segmentation model using my dataset,  what should I do?

Thanks

John

**Comment by YuvalNirkin** [comment]
Use the following repository to train a Caffe FCN model: [https://github.com/shelhamer/fcn.berkeleyvision.org](https://github.com/shelhamer/fcn.berkeleyvision.org)

Yuval

**Comment by rootkit** [comment]
Thanks
