### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by lightbrotherV** [YuvalNirkin/face_swap#33]
thank you for sharing the code!
In "make -j4"  display error:

/root/face_swap_lib/face_swap/face_swap/cnn_3dmm_expr.cpp: In constructor 'face_
swap::CNN3DMMExpr::CNN3DMMExpr(const string&, const string&, const string&, cons
t string&, bool, bool, bool, int)':
/root/face_swap_lib/face_swap/face_swap/cnn_3dmm_expr.cpp:29:20: error: 'make_un
ique' is not a member of 'std'
         fservice = std::make_unique<FaceServices2>();
                    ^
/root/face_swap_lib/face_swap/face_swap/cnn_3dmm_expr.cpp:29:50: error: expected
 primary-expression before '>' token
         fservice = std::make_unique<FaceServices2>();
                                                  ^
/root/face_swap_lib/face_swap/face_swap/cnn_3dmm_expr.cpp:29:52: error: expected
 primary-expression before ')' token
         fservice = std::make_unique<FaceServices2>();
                                                    ^
make[2]: *** [face_swap/CMakeFiles/face_swap.dir/cnn_3dmm_expr.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/root/face_swap_lib/face_swap/face_swap/face_swap_engine_impl.cpp: In constructo
r 'face_swap::FaceSwapEngineImpl::FaceSwapEngineImpl(const string&, const string
&, const string&, const string&, const string&, const string&, const string&, co
nst string&, bool, bool, bool, int)':
/root/face_swap_lib/face_swap/face_swap/face_swap_engine_impl.cpp:47:21: error:m
ake_unique' is not a member of 'std'
   m_cnn_3dmm_expr = std::make_unique<CNN3DMMExpr>(
                     ^
/root/face_swap_lib/face_swap/face_swap/face_swap_engine_impl.cpp:47:49: error:e
xpected primary-expression before '>' token
   m_cnn_3dmm_expr = std::make_unique<CNN3DMMExpr>(
                                                 ^
/root/face_swap_lib/face_swap/face_swap/face_swap_engine_impl.cpp:53:17: error:m
ake_unique' is not a member of 'std'
    m_face_seg = std::make_unique<FaceSeg>(seg_deploy_path,
                 ^
/root/face_swap_lib/face_swap/face_swap/face_swap_engine_impl.cpp:53:41: error:e
xpected primary-expression before '>' token
    m_face_seg = std::make_unique<FaceSeg>(seg_deploy_path,
                                         ^
/root/face_swap_lib/face_swap/face_swap/face_swap_engine_impl.cpp:57:18: error:m
ake_unique' is not a member of 'std'
   m_basel_3dmm = std::make_unique<Basel3DMM>();
                  ^
/root/face_swap_lib/face_swap/face_swap/face_swap_engine_impl.cpp:57:44: error:e
xpected primary-expression before '>' token
   m_basel_3dmm = std::make_unique<Basel3DMM>();
                                            ^
/root/face_swap_lib/face_swap/face_swap/face_swap_engine_impl.cpp:57:46: error:e
xpected primary-expression before ')' token
   m_basel_3dmm = std::make_unique<Basel3DMM>();
                                              ^
make[2]: *** [face_swap/CMakeFiles/face_swap.dir/face_swap_engine_impl.cpp.o] Er
ror 1
make[1]: *** [face_swap/CMakeFiles/face_swap.dir/all] Error 2
make: *** [all] Error 2

I don't what happened. my system is centos. I sure install all Dependencies

**Comment by YuvalNirkin** [comment]
You're missing C++14 support probably due to an old version of g++.
You can try following the solution in #7.
