### ISSUE TITLE
undefiend reference to "boost::system::generic_category()"

### ISSUE THREAD

**Issue by Tord-Zhang** [YuvalNirkin/face_swap#34]
when running "make -j8" for face_swap, this error occurs

**Comment by YuvalNirkin** [comment]
Sounds like you're missing the boost_system library. Try to reinstall boost.

**Comment by Tord-Zhang** [comment]
@YuvalNirkin I fixed this problem and finish the compilation. However,when I run" import face_swap_py" in python, python cannot find the face_swap_py package. I do have import the path to profile

**Comment by Tord-Zhang** [comment]
@YuvalNirkin  this error, "ImportError: /home/imageim/installations/face_swap/interfaces/python/face_swap_py.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE"

**Comment by Tord-Zhang** [comment]
@YuvalNirkin Do you have any idea why this happened? thanks.

**Comment by Tord-Zhang** [comment]
@YuvalNirkin  In python3.5, I get "Segmentation fault (core dumped)" when I run "import face_swap_py"

**Comment by YuvalNirkin** [comment]
Please use Python 2.7, I haven't tested the Python binding with Python 3.x.
