### ISSUE TITLE
failed to use the python interface

### ISSUE THREAD

**Issue by Tord-Zhang** [YuvalNirkin/face_swap#35]
I failed to use the python interface after successful compilation.
Got the error message blow:
`/home/imageim/installations/face_swap/interfaces/python/face_swap_py.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE`

I am sure that I compile the code with python blind. I compile caffe and opencv without cuda. The python version is 2.7. 
I googled this problem, someone said that it is because the python version does not match the boost version when compiling caffe, but I am sure the version match.

**Comment by YuvalNirkin** [comment]
What is your Boost version?

**Comment by phaphuang** [comment]
I also stuck with this message. what is the solution. By the way, I followed the instruction 
`ImportError: /root/installations/face_swap/interfaces/python/face_swap_py.so: undefined symbol: _ZN5boost6python5numpy6detail15get_float_dtypeILi32EEENS1_5dtypeEv`
