### ISSUE TITLE
Where to fetch the model of "model_3dmm_h5" 

### ISSUE THREAD

**Issue by alessandroweiliu** [YuvalNirkin/face_swap#38]
Hi, thanks for your wonderful work. 

When I try to reproduce the result of this work, I do not know where to find the 3dmm h5 model ( I can find the .dat model). 

Would some guys tell me where I can download this model. Thanks a lot!

**Comment by YuvalNirkin** [comment]
```Bash
wget https://github.com/YuvalNirkin/face_swap/releases/download/0.9/3dmm_cnn_resnet_101.zip
```
