### ISSUE TITLE
Installation instructions no longer work

### ISSUE THREAD

**Issue by siphetegis** [YuvalNirkin/face_swap#39]
I tried following the Ubuntu 16.04 setup instructions and I am unable to install the dependencies. When installing boost, it shows unable to install 54 targets. 

I am also unable to install to install Openblas by following the instructions in the setup guide.

Could you or anyone else just try following the instructions on Ubuntu 16.04 and update it so it works? It's a nice paper, but like most other papers, the provided code almost never works because of install issues or outdated libraries.

Thanks

**Comment by YuvalNirkin** [comment]
I can't support problems with installing the dependencies, especially when you don't provide any details. The boost library is a very popular library, I am sure you can find a lot of information online on how to install it.
