### ISSUE TITLE
protobuf version conflict

### ISSUE THREAD

**Issue by czastack** [YuvalNirkin/face_swap#4]
When I build finish and run face_swap_image --cfg test.cfg
I got this error as bellow.
[libprotobuf FATAL google/protobuf/stubs/common.cc:78] This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.3.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/build/mir-pkdHET/mir-0.21.0+16.04.20160330/obj-x86_64-linux-gnu/src/protobuf/mir_protobuf.pb.cc".)
This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.3.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/build/mir-pkdHET/mir-0.21.0+16.04.20160330/obj-x86_64-linux-gnu/src/protobuf/mir_protobuf.pb.cc".)

I have remove the libprotobuf-dev and protobuf-compiler from system and rebuild all the dependencies. But it is the same. Can you give me some advice?

- Ubuntu 16.04
- Boost 1.58
- Qt 5.9
- OpenCV 3.2
- GLEW 2.0
- Eigen 3.0.0
- dlib 18
- find_face_landmarks 1.1	
- face_segmentation 0.9	
- Caffe 1.0

**Comment by YuvalNirkin** [comment]
It seems you still have some residue of the previous version of protobuf.
I would try to do the following:
- Make sure you remove all the old protobuf libraries and headers.
- Caffe or OpenCV might contain a local version of protobuf,  configure them to use your latest protobuf version (3.3.0).
- Do a clean build and install of OpenCV, Caffe, find_face_landmarks, face_segmentation, and face_swap (in this order).

Good luck!

**Comment by czastack** [comment]
When I delete libprotobuf.so.9 and libprotobuf-lite.so.9, the ubuntu desktop crash.
In addition, there is no protobuf 2 installed.
And I don't know how to onfigure Caffe and OpenCV  to use latest protobuf. The opencv-3.2.0 use the protobuf-3.1.0 from source.

**Comment by czastack** [comment]
I found this in internet.

The Mir version in any Ubuntu archive is built with the protobuf version in the archive. The version of protobuf in the Ubuntu 16.04 archive is 2.6.1.

The simplest option is to use libprotobuf-dev as supplied in the archive. If you need to use a more recent version, then you'll need to rebuild any packages that use it, including Mir.

Using a different archive won't help: Even the current 17.04 release only has 3.0.0 of protobuf.

I don't know how to do now.

**Comment by YuvalNirkin** [comment]
Use CMake to configure the libraries to use the right version of protobuf.
The cmake-gui application is especially useful for that.

You can install any version of protobuf you want, the Linux version doesn't matter. Just specify a different install directory instead of the default one.

**Comment by halfkai** [comment]
same problem as well… and I did using cmake build and install in order... still failed :(

**Comment by YuvalNirkin** [comment]
There is no way for me to reproduce this problem :(
If you get a runtime error as mentioned in the first comment, you can try setting the LD_LIBRARY_PATH environment variable with the path to the right protobuf version.

**Comment by YuvalNirkin** [comment]
I am closing this issue. Feel free to open it again if you still have problems with this.
