### ISSUE TITLE
ImportError: ../face_swap_py.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE

### ISSUE THREAD

**Issue by IOEvan** [YuvalNirkin/face_swap#43]
There was a error after I finished the [Ubuntu Installation Guide](https://github.com/YuvalNirkin/face_swap/wiki/Ubuntu-Installation-Guide).

When I using "import face_swap_py", it threw
`ImportError: /home/python/code/face_swap/interfaces/python/face_swap_py.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE`

And the version of python is `Python 2.7.15 |Anaconda, Inc.|`.  The "PYTHON_LIBRARIES" in the "Makefile" is default：`PYTHON_LIBRARIES := boost_python-py27 python2.7`.

So how can I to deal with this error?

**Comment by lhlmgr** [comment]
+1

**Comment by longhopefor** [comment]
can i ask how do you solve the problem? i have the same question with you

**Comment by IOEvan** [comment]
> 
> 
> can i ask how do you solve the problem? i have the same question with you

Sorry, it's too long for me to remember this question. :)

**Comment by zhuhaozh** [comment]
Hi, @longhopefor @YuvalNirkin 
i met the same problem, anyone knows how to solve this?

**Comment by zhuhaozh** [comment]
> Hi, @longhopefor @YuvalNirkin
> i met the same problem, anyone knows how to solve this?

Solved by installing this on a docker image. 
I think it may cause by multiple versions of python, and on the docker image it has a pure python env.

**Comment by YuvalNirkin** [comment]
Make sure the boost python and numpy libraries actually exist and that cmake did not find another boost version instead.
