### ISSUE TITLE
face_swap_image: command not found

### ISSUE THREAD

**Issue by ovsilya** [YuvalNirkin/face_swap#45]
Hello guys,

I'm trying to run 

```
cd path/to/face_swap/bin
face_swap_image --cfg test.cfg
```

command to do the swapping but it produces the following error:
`face_swap_image: command not found`

**Comment by iacopomasi** [comment]
Are you sure that you compiled correctly the source code to produce the final binary file?
Try to sift through the directories and see where the bin is the binary file you are looking for.

**Comment by ovsilya** [comment]
> Are you sure that you compiled correctly the source code to produce the final binary file?
> Try to sift through the directories and see where the bin is the binary file you are looking for.

@iacopomasi yeah, you're right, I was going through the wrong path. All works now, thanks!
