### ISSUE TITLE
the video generated by image2video is shaking .

### ISSUE THREAD

**Issue by rexxar-liang** [YuvalNirkin/face_swap#47]
Hello, 
    Our repository is Amazing！We can swap a whole video in 1 min!
    When we use face_swap_image2video.cpp, we have a problem and hope your optimize opinion.
    We found that when the video is playing, the face will shake somehow. Is there any good way to remove this sway?

    Many thanks!

**Comment by YuvalNirkin** [comment]
This repository is mainly for image-to-image face swapping.
You should wait for our follow up paper's code which will support video face swapping: [https://nirkin.com/fsgan](https://nirkin.com/fsgan)

**Comment by rexxar-liang** [comment]
Great! Hope to try the video face swapping when the code is ready. 
Thanks!

**Comment by wackxu** [comment]
@YuvalNirkin That is great. When will the code  be ready? I can't wait to try it out.

**Comment by rootkit** [comment]
@YuvalNirkin Wow!  fsgan is great, img blending is difficult and complex. I think that is a great tech.

**Comment by ghost** [comment]
@YuvalNirkin will FSGAN code be released before or after iccv 2019?

**Comment by decajcd** [comment]
> Hello,
> Our repository is Amazing！We can swap a whole video in 1 min!
> When we use face_swap_image2video.cpp, we have a problem and hope your optimize opinion.
> We found that when the video is playing, the face will shake somehow. Is there any good way to remove this sway?
> 
> ```
> Many thanks!
> ```
Can you share this file?
fatal error: face_swap/face_swap_export.h: No such file or directory

**Comment by MengXinChengXuYuan** [comment]
@YuvalNirkin Hi any plan for fsgan ?

**Comment by rexxar-liang** [comment]
@YuvalNirkin 
Hi, there is a new faces waping paper come out,  ”FaceShifter: Towards High Fidelity And Occlusion Aware Face Swapping“[https://arxiv.org/pdf/1912.13457.pdf].
The faces show in the paper looks good, but I think for video scenario， this new paper will not work fine(may shaking)。
FSGAN support video scenario which is much more attracting me.
Any new plan for open source? I eager to try it out.

Thanks.

**Comment by YuvalNirkin** [comment]
@rexxar-liang Yes, I also suspect that similar to other attribute-based algorithms such as RSGAN and FSNet, this method won't be able to generate temporally consistent results suitable for video face swapping. It's a very interesting work nonetheless.

The FSGAN code is ready but unfortunately we have some legal issues concerning the release.

Sorry for the inconvenience,
Yuval

**Comment by puppet101** [comment]
> @rexxar-liang Yes, I also suspect that similar to other attribute-based algorithms such as RSGAN and FSNet, this method won't be able to generate temporally consistent results suitable for video face swapping. It's a very interesting work nonetheless.
> 
> The FSGAN code is ready but unfortunately we have some legal issues concerning the release.
> 
> Sorry for the inconvenience,
> Yuval

So, do you mean that the code will not be released?
