### ISSUE TITLE
ubuntu run out of memory

### ISSUE THREAD

**Issue by longhopefor** [YuvalNirkin/face_swap#48]
environment:
ubuntu 18.04 with 4cpu 8G ram, no gpu
python2.7

question:
when i run the application: face_swap_image, it killed by the system because of out of memory, is there any problem or how much memory should i use to run the application?

**Comment by ghost** [comment]
@longhopefor have you tried https://github.com/shaoanlu/fewshot-face-translation-GAN
it only needs a single image for face swapping and has a google colab notebook to try with free gpu

**Comment by longhopefor** [comment]
thank you for your reply! I will try it
