### ISSUE TITLE
libraries may not be found correctly

### ISSUE THREAD

**Issue by Haylemicheal** [YuvalNirkin/face_swap#50]
i got a warning while buildning the cmake file on the cafee installation procedure "cmake -DCPU_ONLY=ON -DBUILD_python=OFF -DBUILD_python_layer=OFF -DCMAKE_INSTALL_PREFIX=/usr/local .. "

The output says 
"CMake Warning at examples/CMakeLists.txt:11 (add_executable):
  Cannot generate a safe runtime search path for target
  convert_mnist_siamese_data because files in some directories may conflict
  with libraries in implicit directories:
  runtime library [libglog.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in: /anaconda3/envs/faceswap/lib

runtime library [libgflags.so.2.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in: /anaconda3/envs/faceswap/lib

runtime library [libleveldb.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in: /anaconda3/envs/faceswap/lib
Some of these libraries may not be found correctly.

**Comment by YuvalNirkin** [comment]
Life is too short to worry about warnings :wink:
More importantly does it work?

**Comment by Haylemicheal** [comment]
It doesn't work. I got an error while making the "make all -j8" instruction in the caffee  compilation process. The error says:
CMakeFiles/caffe.bin.dir/caffe.cpp.o: In function `train()':
caffe.cpp:(.text+0x23df): undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Add()'
caffe.cpp:(.text+0x305d): undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Clear()'
caffe.cpp:(.text+0x3515): undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Clear()'
caffe.cpp:(.text+0x3524): undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Add()'
../lib/libcaffe.so.1.0.0: undefined reference to `google::protobuf::internal::ArenaImpl::AllocateAlignedAndAddCleanup(unsigned long, void (*)(void*))'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::thread::start_thread_noexcept()'
../lib/libcaffe.so.1.0.0: undefined reference to `google::protobuf::RepeatedField<float>::Add(float const&)'
../lib/libcaffe.so.1.0.0: undefined reference to `google::protobuf::internal::AddDescriptors(google::protobuf::internal::DescriptorTable const*)'
../lib/libcaffe.so.1.0.0: undefined reference to `google::protobuf::RepeatedField<unsigned int>::~RepeatedField()'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::thread::detach()'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::detail::thread_data_base::~thread_data_base()'
../lib/libcaffe.so.1.0.0: undefined reference to `google::protobuf::internal::WireFormatLite::UInt32Size(google::protobuf::RepeatedField<unsigned int> const&)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::filesystem::path::replace_extension(boost::filesystem::path const&)'
../lib/libcaffe.so.1.0.0: undefined reference to `google::protobuf::RepeatedField<long>::~RepeatedField()'
../lib/libcaffe.so.1.0.0: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Get(int) const'

**Comment by clmrie** [comment]
@YuvalNirkin Hi sir! Could you please tell me how could I get the "face_swap_export.h" file ?

**Comment by YuvalNirkin** [comment]
@Haylemicheal  You are apparently missing the protobuf library.
@clmrie It is generated in the make process.

**Comment by clmrie** [comment]
@YuvalNirkin Thank you for answer. Could you explain me how to do the "make process"? Sorry for the nooby questions.

**Comment by YuvalNirkin** [comment]
Follow the installation guide:
[https://github.com/YuvalNirkin/face_swap/wiki/Ubuntu-Installation-Guide](https://github.com/YuvalNirkin/face_swap/wiki/Ubuntu-Installation-Guide)
