### ISSUE TITLE
Biding error---Configuring incomplete, errors occurred

### ISSUE THREAD

**Issue by jackob234** [YuvalNirkin/face_swap#52]
Hi i triad  too build your progrem whit all steps but i get fallowing error on Cmake version 3.16. that is latest version  from there web site.

CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Boost (missing: filesystem program_options regex timer
  thread chrono) (found version "1.71.0")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.16/Modules/FindBoost.cmake:2162 (find_package_handle_standard_args)
  CMakeLists.txt:64 (find_package)

Configuring incomplete, errors occurred!

**Comment by YuvalNirkin** [comment]
It seems like you're missing the boost library or you installed it somewhere CMake can't find it.
