### ISSUE TITLE
"Qt5::Widgets", the target was not found.

### ISSUE THREAD

**Issue by daili0015** [YuvalNirkin/face_swap#8]
My system is Ubuntu14.04
I download  qt-everywhere-opensource-src-5.6.0 and install follow this https://wiki.qt.io/Building_Qt_5_from_Git
————————————
unzip it and : 
./configure -prefix $PWD/qtbase -opensource -nomake tests               (this took hours)
make
make install
————————————
but when i cmake "face_swap", error occurs ：
————————————————————————————————————
`-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   filesystem
--   program_options
--   regex
--   timer
-- Found OpenCV: /usr/local (found version "3.2.0") found components:  highgui imgproc imgcodecs calib3d photo
-- C++11 activated.
CMake Warning at CMakeLists.txt:67 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.

-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
-- Found HDF5: /usr/lib/x86_64-linux-gnu/libhdf5_cpp.so;/usr/lib/x86_64-linux-gnu/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.8.11") found components:  HL
-- Found HDF5: /usr/lib/x86_64-linux-gnu/libhdf5_cpp.so;/usr/lib/x86_64-linux-gnu/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.8.11") found components:  CXX
-- Found Eigen3: /usr/local/include/eigen3 (Required is at least version "2.91.0")
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so
-- Found GLEW: /usr/include
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.6")
-- Configuring done
CMake Error at face_swap_image/CMakeLists.txt:2 (add_executable):
  Target "face_swap_image" links to target "Qt5::Widgets" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at face_swap_batch/CMakeLists.txt:2 (add_executable):
  Target "face_swap_batch" links to target "Qt5::Widgets" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
`
————————————————————————————————————
How can i add Qt5's path into the project ? 
I tried "~/.bashrc"  "/home/face_swap-master/CMakeLists.txt" , that don't help.
Qt5 path is "/home/qt-everywhere-opensource-src-5.6.0"

**Comment by YuvalNirkin** [comment]
You have to set the CMake variable Qt5Widgets_DIR to the path containing Qt5WidgetsConfig.cmake.
This should be found somewhere in the installation directory of Qt.

**Comment by daili0015** [comment]
Thanks for your timely and helpful advice！
I solved this problem by add path to "/home/face_swap-master/CMakeLists.txt"
———————————————————————————————————
`set(CMAKE_PREFIX_PATH "/home/qt-everywhere-opensource-src-5.6.0/qtbase")`
———————————————————————————————————
I met error because i add a wrong path, though don't know why, but obviously “qtbase” is the key path instead of its father path.
Hope this helps to those who install Qt5 with a source file :([http://download.qt.io/official_releases/qt/5.6/5.6.0/single/])
Instead of a ".run" file([http://download.qt.io/official_releases/qt/5.6/5.6.0/])
